### ISSUE TITLE
[Suggestion] Gun Bonsai: Add this text to localization file

### ISSUE THREAD

**Issue by Blueberryy** [ToxicFrog/doom-mods#15]
I'm planning to do russian translation for this mod and i would like to translate HUD elements like "Lv.", "XP" and base Doom, Heretic, Hexen, Strife, Chex Quest, Harmony and Chex Quest 3 weapon names.

**Comment by ToxicFrog** [comment]
The base weapon names come from the base LANGUAGE lump, as far as I know, I just retrieve them using GetTag(). I can definitely pull the rest of the incidental UI terms out into LANGUAGE lumps though!

**Comment by ToxicFrog** [comment]
HUD/menu elements should be in the LANGUAGE lumps as of c0e065c2c6b9bb3c41ab43e443f0cfba8a89758a -- look in LANGUAGE.en-menu for the english versions.

Base weapon names come from the engine and I've confirmed that they get translated properly if you change the gzDoom language. Note that the `Type:` display will always display both the translated weapon name and the internal class name, and the latter doesn't change and is usually in english, so (e.g.) the plasma rifle will show up as "Плазменная пушка (PlasmaRifle)" -- this is so that people reporting bugs or compatibility issues can easily report the internal classname of the weapon they're having problems with. The HUD should always display the translated name.

**Comment by Blueberryy** [comment]
> HUD/menu elements should be in the LANGUAGE lumps as of c0e065c2c6b9bb3c41ab43e443f0cfba8a89758a -- look in LANGUAGE.en-menu for the english versions.
> 
> Base weapon names come from the engine and I've confirmed that they get translated properly if you change the gzDoom language. Note that the `Type:` display will always display both the translated weapon name and the internal class name, and the latter doesn't change and is usually in english, so (e.g.) the plasma rifle will show up as "Плазменная пушка (PlasmaRifle)" -- this is so that people reporting bugs or compatibility issues can easily report the internal classname of the weapon they're having problems with. The HUD should always display the translated name.

Thank you for the info and adding those to translation files! I will create Pull Request in a few
