### ISSUE TITLE
[Bug] Player won't take area damage in E1M8's ending room

### ISSUE THREAD

**Issue by Dudejo** [ToxicFrog/doom-mods#22]
<details>
  <summary>SCREENSHOT</summary>

![image](https://github.com/ToxicFrog/doom-mods/assets/38837115/32a0f04d-9e67-444d-9817-365cfe6e706a)
</details>

I'm using GZDoom 4.8.2 with GunBonsai 0.10.1, playing Ultimate Doom.

As I said in the title, I seemingly can't take any area damage once I teleport into the E1M8 ending room where the player is supposed to die. I've included a screenshot of my character build if it's any help.

**Comment by ToxicFrog** [comment]
Huh, that's really weird. Having two levels of Hazard Suit should cause you take significantly _reduced_ damage from the hurtfloor, but not _none_. And in my testing I do in fact still take damage from it and eventually die -- and even if Hazard Suit was glitching out and blocking all hurtfloor damage, the group of enemies you teleport into should still be hurting you.

Can you send me the save file? I can load it up with a debug build and get a better idea of what's happening.

It might also be worth turning off individual upgrades from the status screen, and seeing if there's a specific one that, when turned off, causes things to start working again.

**Comment by Dudejo** [comment]
[save file.zip](https://github.com/ToxicFrog/doom-mods/files/12141190/save.file.zip)

I had to rebuild the character but I reproduced the bug.

Although this particular save also needs LazyPoints 0.4, I forgot to turn it off X(

**Comment by ToxicFrog** [comment]
Ok, with that and the save file I was able to diagnose this. It is indeed Infernal Forge causing it, and while it will eventually wear off, you'll have to stand around for about ten minutes before that happens.

It's a combination of issues that result in this behaviour:
- the buff is applied at a rate of 1 second per 100 damage dealt times the buff level; at level 3, as long as you're dealing at least 34 damage/second, you will be accumulating buff duration faster than it's ticking down
- the buff duration has no diminishing returns
- the defensive aspect of the buff, unlike other defence buffs in GB, can reduce damage to 0
- using the buff doesn't shorten the duration

So how did it get like this? Well, early versions of the buff were expendable -- dealing or taking damage would reduce the remaining duration by 1 second. The problem that emerged from this was that unless you had a really high level on it, whatever you gained from one attack would be used up immediately by the next attack, so it effectively functioned as a simple damage bonus with no ongoing effects. To address this, I changed it so that it was purely time-based, but clearly didn't give it as much balance testing as it needed -- probably because, in all honesty, Fire is the tree I use least, and when I do use it I'm much more likely to put Conflagration on a weapon.

The fix is probably some combination of:
- diminishing returns to the rate at which stacks are accumulated (or have them decay faster the more you have; these should be equivalent)
- damage taken reduces the buff duration in proportion (dealing damage still doesn't)
- don't let it reduce damage below 1

**Comment by ToxicFrog** [comment]
I'm testing a balance rework for this that should land in the next release.

**Comment by ToxicFrog** [comment]
Fixed-ish in 382d22e6c41a8b1c29ed2ec6be164437cbe240de, although I may want to add diminishing returns of some sort to the max duration to keep it from getting silly when people are playing slaughterwads and getting double-digit levels for individual upgrades and stuff.
