### ISSUE TITLE
Crash on startup with Gun Bonsai + Brutal Doom Platinum

### ISSUE THREAD

**Issue by pbates5** [ToxicFrog/doom-mods#26]
When loaded with Brutal Doom Platinum, the game crashes before it reaches the main menu. Just before the BDP loading screen finishes, an unhelpful gray dialogue box pops up that just says "OK", and after clicking it the game crashes back to the delta touch main menu

**Comment by ToxicFrog** [comment]
After a bit of testing I've been able to repro this locally. It's not a problem with DeltaTouch specifically. This also means that I get actual log output when it crashes, which I gather you don't get with DT.

The issue, specifically, is that BDP looks for lumps called "WeaponInfo" to read information about weapon replacements. Gun Bonsai contains a zscript lump called `WeaponInfo.zsc`, and BDP ends up finding that in addition to the `WeaponInfo.txt` that BDP contains. It tries to parse it as a BDP WeaponInfo file, can't (because it's ZScript source code), and rather than gracefully skipping that lump, crashes hard.

This is not a problem unique to Gun Bonsai; _any_ mod containing a file named `WeaponInfo` that isn't a BDP weapon replacement list will crash BDP 3.x.

However, it looks like this is [already fixed at HEAD](https://github.com/EmeraldCoasttt/BrutalDoomPlatinum/commit/6f615340ee25a2fa1b69c6e1c69825979208e942) in BDP, so the next release (4.1?) should fix it on their end.
